#!/usr/bin/env bash
# Download self-hosted JetBrains Mono + Space Grotesk woff2 files.
# Run once on your VPS (or local dev machine) inside this directory.
# Output: fonts/*.woff2 + fonts.css ready to drop on your web root.

set -euo pipefail

cd "$(dirname "$0")"
mkdir -p fonts

UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
CSS_URL='https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Space+Grotesk:wght@400;500;600;700&display=swap'

echo "[1/3] Fetching Google Fonts CSS..."
curl -s -H "User-Agent: $UA" "$CSS_URL" > _remote.css

echo "[2/3] Filtering to latin + latin-ext + vietnamese subsets and rewriting URLs..."
python3 - <<'PY'
import re, urllib.request, urllib.parse, os, sys

WANT_SUBSETS = {"latin", "latin-ext", "vietnamese"}
with open("_remote.css", encoding="utf-8") as f:
    css = f.read()

# Each @font-face block is preceded by a comment like /* latin */
blocks = re.split(r'(/\*\s*[a-z-]+\s*\*/)', css)
out_blocks = []
current_subset = None
url_re = re.compile(r'url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)')

for chunk in blocks:
    m = re.match(r'/\*\s*([a-z-]+)\s*\*/', chunk.strip())
    if m:
        current_subset = m.group(1)
        continue
    if "@font-face" not in chunk:
        continue
    if current_subset not in WANT_SUBSETS:
        continue
    url_match = url_re.search(chunk)
    if not url_match:
        continue
    remote = url_match.group(1)
    family_match = re.search(r"font-family:\s*'([^']+)'", chunk)
    weight_match = re.search(r"font-weight:\s*(\d+)", chunk)
    family_slug = family_match.group(1).lower().replace(" ", "-") if family_match else "font"
    weight = weight_match.group(1) if weight_match else "400"
    local_name = f"{family_slug}-{weight}-{current_subset}.woff2"
    local_path = os.path.join("fonts", local_name)
    if not os.path.exists(local_path):
        print(f"  downloading {local_name}")
        req = urllib.request.Request(remote, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req) as r, open(local_path, "wb") as out:
            out.write(r.read())
    rewritten = chunk.replace(remote, f"/fonts/{local_name}")
    out_blocks.append(rewritten.strip())

with open("fonts.css", "w", encoding="utf-8") as f:
    f.write(
        "/* Self-hosted JetBrains Mono + Space Grotesk (latin, latin-ext, vietnamese). */\n"
        "/* Generated by landing/self-host-fonts/download.sh */\n\n"
    )
    f.write("\n\n".join(out_blocks))
    f.write("\n")

print(f"  wrote fonts.css ({sum(os.path.getsize(os.path.join('fonts', f)) for f in os.listdir('fonts')) // 1024} KB of woff2)")
PY

rm -f _remote.css

echo "[3/3] Done."
echo
echo "Files generated:"
ls -lh fonts/*.woff2 2>/dev/null | awk '{print "  ", $9, $5}'
echo "  $(pwd)/fonts.css"
echo
echo "Next steps (see README.md in this directory):"
echo "  1. Upload fonts/ and fonts.css to your web root (e.g. /var/www/site/)"
echo "  2. Replace the Google Fonts <link> in your HTML with: <link rel=\"stylesheet\" href=\"/fonts.css\">"
echo "  3. Remove the two preconnect lines pointing to fonts.googleapis.com / fonts.gstatic.com"
