"""HTML / Markdown report generator — Ultra tier.

Produces standalone HTML tearsheets and Markdown briefings that
aggregate the gold-mcp tool outputs into a polished, human-readable
artifact. Files are written to disk and the path is returned.
"""
from __future__ import annotations

import os
import time
from html import escape
from pathlib import Path


def _reports_dir() -> Path:
    raw = os.environ.get("GOLD_MCP_REPORTS_DIR", "").strip()
    base = Path(raw).expanduser() if raw else Path.home() / ".cache" / "gold-mcp" / "reports"
    base.mkdir(parents=True, exist_ok=True)
    return base


_HTML_TMPL = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>{title}</title>
<style>
:root {{
  --bg:#0b0d10; --panel:#14171c; --border:#232830; --text:#e7ebf0;
  --dim:#97a0ab; --accent:#d4a23a; --green:#5dd39e; --red:#e57373;
}}
body {{ background:var(--bg); color:var(--text); font-family:-apple-system,Segoe UI,Roboto,sans-serif; margin:0; padding:24px; }}
.container {{ max-width:980px; margin:0 auto; }}
h1 {{ font-size:28px; margin:0 0 8px; color:var(--accent); }}
.subhead {{ color:var(--dim); margin:0 0 28px; font-size:14px; }}
.section {{ background:var(--panel); border:1px solid var(--border); border-radius:8px; padding:18px 20px; margin-bottom:16px; }}
.section h2 {{ font-size:16px; margin:0 0 12px; color:var(--accent); letter-spacing:0.04em; text-transform:uppercase; }}
.kv {{ display:grid; grid-template-columns:1fr 1fr; gap:6px 18px; font-size:14px; }}
.kv span:nth-child(odd) {{ color:var(--dim); }}
.bias-bullish {{ color:var(--green); font-weight:600; }}
.bias-bearish {{ color:var(--red); font-weight:600; }}
.bias-neutral {{ color:var(--dim); font-weight:600; }}
pre {{ background:#0b0d10; border:1px solid var(--border); padding:12px; overflow:auto; font-size:12px; border-radius:6px; }}
.footer {{ margin-top:24px; color:var(--dim); font-size:12px; text-align:center; }}
ul.events {{ padding-left:18px; margin:0; font-size:13px; color:var(--text); }}
ul.events li {{ padding:3px 0; }}
.badge {{ display:inline-block; background:#1b1f26; border:1px solid var(--border); color:var(--accent); padding:3px 10px; border-radius:12px; font-size:11px; letter-spacing:0.08em; text-transform:uppercase; margin-right:6px; }}
</style></head><body>
<div class="container">
<h1>{title}</h1>
<p class="subhead">{subhead}</p>
{sections}
<p class="footer">Generated by gold-mcp Ultra tier · Educational use only · Not financial advice</p>
</div></body></html>"""


def _bias_class(bias: str) -> str:
    if "bull" in bias.lower():
        return "bias-bullish"
    if "bear" in bias.lower():
        return "bias-bearish"
    return "bias-neutral"


def _section(title: str, body: str) -> str:
    return f'<div class="section"><h2>{escape(title)}</h2>{body}</div>'


def _kv(pairs: list[tuple[str, str]]) -> str:
    rows = "".join(f"<span>{escape(str(k))}</span><span>{escape(str(v))}</span>" for k, v in pairs)
    return f'<div class="kv">{rows}</div>'


def generate_html_tearsheet(symbol: str = "XAUUSD") -> dict:
    """Build a polished HTML tearsheet snapshot.

    Aggregates: price, MTF alignment, SMC bias, regime, key correlations,
    macro context, VN parity. Writes to disk and returns the path + a
    text summary suitable for inline LLM display.
    """
    from . import analyst, analytics, gold_data, macro_data, mtf, pro_tools, regime, smart_money
    from .adapters import vn_macro as vn_macro_adapter

    price = gold_data.get_gold_price()
    bars = gold_data.get_gold_ohlcv(timeframe="1h", lookback=120)
    macro = macro_data.get_macro_context()
    snapshot = analyst.gold_market_snapshot()
    season = analytics.get_seasonality(group_by="dow")
    vn = vn_macro_adapter.get_vn_macro()

    smc_result = None
    regime_result = None
    if "error" not in bars:
        smc_result = smart_money.smc_full_scan(bars["bars"])
        regime_result = regime.classify_regime([b["close"] for b in bars["bars"]])

    mtf_result = mtf.mtf_alignment()
    setups = pro_tools.get_gold_setups()

    sections = []

    # Header / Price
    pair_rows = [
        ("Last close", f"{price.get('last', 'n/a')}"),
        ("24h change", f"{price.get('change_24h_pct', 'n/a')}%"),
        ("Intraday high", f"{price.get('intraday_high', 'n/a')}"),
        ("Intraday low", f"{price.get('intraday_low', 'n/a')}"),
        ("Asof (UTC)", str(price.get("asof", "n/a"))),
    ]
    sections.append(_section("Price", _kv(pair_rows)))

    # SMC bias
    if smc_result and "composite_bias" in smc_result:
        bias = smc_result["composite_bias"]
        smc_rows = [
            ("Composite bias", f'<span class="{_bias_class(bias)}">{bias}</span>'),
            ("Bias score", smc_result.get("composite_bias_score")),
            ("Active order blocks", smc_result.get("order_blocks", {}).get("n_active")),
            ("Unfilled FVGs", smc_result.get("fair_value_gaps", {}).get("n_unfilled")),
            ("Liquidity sweeps detected", smc_result.get("liquidity_sweeps", {}).get("n_sweeps")),
            ("Current structure trend", smc_result.get("market_structure", {}).get("current_trend")),
        ]
        rows_html = "".join(
            f"<span>{escape(str(k))}</span><span>{v}</span>" for k, v in smc_rows
        )
        sections.append(_section("Smart Money (SMC)", f'<div class="kv">{rows_html}</div>'))

    # Regime
    if regime_result and "composite_regime" in regime_result:
        regime_rows = [
            ("Composite regime", regime_result["composite_regime"]),
            ("Hurst exponent", regime_result["hurst"].get("hurst")),
            ("Variance ratio", regime_result["variance_ratio"].get("variance_ratio")),
            ("VR z-stat", regime_result["variance_ratio"].get("z_stat")),
            ("Trading implication", regime_result.get("trading_implication")),
        ]
        sections.append(_section("Regime", _kv(regime_rows)))

    # MTF
    if "error" not in mtf_result:
        mtf_rows = [
            ("Composite", mtf_result.get("composite")),
            ("Alignment score", f'{mtf_result.get("alignment_score")}/100'),
            ("D1 trend", mtf_result["d1_trend"]["direction"]),
            ("H4 trend", mtf_result["h4_trend"]["direction"]),
            ("H1 momentum", mtf_result["h1_momentum"]["direction"]),
            ("Trading implication", mtf_result.get("trading_implication")),
        ]
        sections.append(_section("Multi-Timeframe Alignment", _kv(mtf_rows)))

    # Macro
    if "error" not in macro:
        macro_rows = []
        for k, v in macro.get("data", {}).items():
            macro_rows.append((k, f"{v.get('last', 'n/a')} ({v.get('change_pct', 0):+.2f}%)"))
        sections.append(_section("Macro Context", _kv(macro_rows)))

    # Setups
    if "error" not in setups:
        setup_rows = [
            ("Bullish confluence", setups.get("bullish_confluence")),
            ("Bearish confluence", setups.get("bearish_confluence")),
            ("RSI 14", setups.get("rsi_14")),
            ("Bollinger signal", setups.get("bollinger_signal")),
            ("Ichimoku cloud", setups.get("ichimoku_cloud_position")),
        ]
        sections.append(_section("Setup Scanner", _kv(setup_rows)))

    # VN parity
    if vn and "world_parity_gold" in vn:
        p = vn["world_parity_gold"]
        vn_rows = [
            ("World-parity VND/tael", f'{p.get("vnd_per_tael_millions", "n/a")}M'),
            ("USD/VND", vn.get("fx_rates", {}).get("USDVND", {}).get("last")),
        ]
        sections.append(_section("Vietnam Context", _kv(vn_rows)))

    # Seasonality top bucket
    if "buckets" in season:
        top_bucket = max(season["buckets"].items(),
                         key=lambda x: x[1]["mean_return_bps"])
        bot_bucket = min(season["buckets"].items(),
                         key=lambda x: x[1]["mean_return_bps"])
        season_rows = [
            ("Best DOW", f"{top_bucket[0]} ({top_bucket[1]['mean_return_bps']:+.1f} bps)"),
            ("Worst DOW", f"{bot_bucket[0]} ({bot_bucket[1]['mean_return_bps']:+.1f} bps)"),
        ]
        sections.append(_section("Seasonality (Day of Week)", _kv(season_rows)))

    # Render
    now = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    html = _HTML_TMPL.format(
        title=f"{symbol} Tearsheet — {now}",
        subhead="Aggregated read from gold-mcp Ultra tier: price, MTF, SMC, regime, macro, VN context.",
        sections="\n".join(sections),
    )
    fname = f"tearsheet_{symbol}_{int(time.time())}.html"
    path = _reports_dir() / fname
    path.write_text(html, encoding="utf-8")
    return {
        "symbol": symbol,
        "path": str(path),
        "size_bytes": path.stat().st_size,
        "n_sections": len(sections),
        "summary_bullets": snapshot.get("summary_bullets", []),
    }


def generate_markdown_briefing(symbol: str = "XAUUSD") -> dict:
    """Plain Markdown briefing — same content as tearsheet, portable."""
    from . import gold_data, mtf, regime, smart_money

    price = gold_data.get_gold_price()
    bars = gold_data.get_gold_ohlcv(timeframe="1h", lookback=120)
    mtf_r = mtf.mtf_alignment()
    smc_r = None
    regime_r = None
    if "error" not in bars:
        smc_r = smart_money.smc_full_scan(bars["bars"])
        regime_r = regime.classify_regime([b["close"] for b in bars["bars"]])

    now = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    lines = [
        f"# Gold ({symbol}) Daily Briefing — {now}",
        "",
        "## Price",
        f"- Last close: **{price.get('last', 'n/a')}**",
        f"- 24h change: **{price.get('change_24h_pct', 'n/a')}%**",
        f"- Intraday high/low: {price.get('intraday_high')} / {price.get('intraday_low')}",
        "",
    ]
    if mtf_r and "error" not in mtf_r:
        lines += [
            "## Multi-Timeframe Alignment",
            f"- Composite: **{mtf_r.get('composite')}** ({mtf_r.get('alignment_score')}/100)",
            f"- D1: {mtf_r['d1_trend']['direction']}, H4: {mtf_r['h4_trend']['direction']}, H1: {mtf_r['h1_momentum']['direction']}",
            f"- *{mtf_r.get('trading_implication')}*",
            "",
        ]
    if smc_r and "composite_bias" in smc_r:
        lines += [
            "## Smart Money (SMC)",
            f"- Composite bias: **{smc_r['composite_bias']}** (score {smc_r.get('composite_bias_score')})",
            f"- Active order blocks: {smc_r['order_blocks'].get('n_active', 0)}",
            f"- Unfilled FVGs: {smc_r['fair_value_gaps'].get('n_unfilled', 0)}",
            f"- Liquidity sweeps: {smc_r['liquidity_sweeps'].get('n_sweeps', 0)}",
            "",
        ]
    if regime_r and "composite_regime" in regime_r:
        lines += [
            "## Regime",
            f"- Composite regime: **{regime_r['composite_regime']}**",
            f"- Hurst: {regime_r['hurst'].get('hurst')} | VR: {regime_r['variance_ratio'].get('variance_ratio')}",
            f"- *{regime_r.get('trading_implication')}*",
            "",
        ]
    lines += [
        "---",
        "*Generated by gold-mcp Ultra tier. Educational use only. Not financial advice.*",
    ]
    md = "\n".join(lines)
    fname = f"briefing_{symbol}_{int(time.time())}.md"
    path = _reports_dir() / fname
    path.write_text(md, encoding="utf-8")
    return {"symbol": symbol, "path": str(path), "size_bytes": path.stat().st_size,
            "markdown": md}
